if(EXISTS "/Users/stevenpillings/Code/crosspoint-reader-todo/build-test/utf8_compose/Utf8ComposeTest[1]_tests.cmake")
  include("/Users/stevenpillings/Code/crosspoint-reader-todo/build-test/utf8_compose/Utf8ComposeTest[1]_tests.cmake")
else()
  add_test(Utf8ComposeTest_NOT_BUILT Utf8ComposeTest_NOT_BUILT)
endif()
