if(EXISTS "/Users/stevenpillings/Code/crosspoint-reader-todo/build-test/differential_rounding/DifferentialRoundingTest[1]_tests.cmake")
  include("/Users/stevenpillings/Code/crosspoint-reader-todo/build-test/differential_rounding/DifferentialRoundingTest[1]_tests.cmake")
else()
  add_test(DifferentialRoundingTest_NOT_BUILT DifferentialRoundingTest_NOT_BUILT)
endif()
